# Stage 1
# Build docker image of react app
FROM node:18-alpine3.16 as build
WORKDIR /modelo_prod
COPY package*.json .
# install and cache app dependencies
RUN yarn
# Copy 
COPY . .
EXPOSE 3002
CMD ["yarn", "start"]
#CMD ["yarn", "start"]

# Stage 2
# Copy the react app build above in nginx
#FROM nginx:1.22.0-alpine
#COPY nginx.conf /etc/nginx/conf.d/default.conf


#WORKDIR /usr/share/nginx/html
#COPY docker-entrypoint.sh .
# remove default nginx static assets
#RUN rm -rf ./*
# copy static files
#COPY --from=build /app/build .

##expose ports
#EXPOSE 80 443

## containers run nginx with global directives and daemon off
#ENTRYPOINT ["nginx", "-g", "daemon off;"]
##Renew certbot:
##### #C#M#D ["/usr/share/nginx/html/docker-entrypoint.sh"] 

