name: CARLITOS CI
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install --global yarn
      - run: CI=false
      - run: yarn install
      - run: yarn build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} //institutodefelicibus.com.br
          REMOTE_USER: ${{ secrets.REMOTE_USER }} //root
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }} //22022
          #TARGET: ${{ secrets.REMOTE_TARGET }}
          TARGET: /home/carlos/produto.carlosdj.com.br/build/

      # - name: Post Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #       host: ${{ secrets.REMOTE_HOST }}
      #       username: ${{ secrets.REMOTE_USER }}
      #       key: ${{ secrets.SSH_PRIVATE_KEY }}
      #       port: ${{ secrets.REMOTE_PORT }}
      #       # script: | 
      #       #   cd /home/wwinst/nodeapp_test
      #       #   yarn restart
      
    